// Add Data ActionTypes
export const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";
export const ADD_PRODUCTS_SUCCSESS = "ADD_PRODUCTS_SUCCSESS";
export const PRODUCTS_FAILURE = "PRODUCTS_FAILURE";

//Get Data ActionTypes
export const DETADM_PRODUCTS_SUCCSESS = "DETADM_PRODUCTS_SUCCSESS";
